# Clase 6 - Unidad 3
Aplicaciones Computacionales en Ing.

* Franco Mansilla Ibáñez (www.francomansilla.com)

## 1. PIP - Gestor de paquetes

A continuación se muestra un listado de los comandos principales que podemos utilizar con pip. Ten en cuenta que en los ejemplos se esta utilizando el paquete externo `pandas`.

* Actualización de PIP

In [1]:
pip install --upgrade pip

Requirement already satisfied: pip in /Users/francomansilla/opt/anaconda3/lib/python3.9/site-packages (24.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Requirement already satisfied: pandas in /Users/francomansilla/opt/anaconda3/lib/python3.9/site-packages (2.1.0)
Requirement already satisfied: numpy>=1.22.4 in /Users/francomansilla/opt/anaconda3/lib/python3.9/site-packages (from pandas) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/francomansilla/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/francomansilla/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/francomansilla/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in /Users/francomansilla/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip list

Package                            Version
---------------------------------- --------------------
absl-py                            1.0.0
aiohttp                            3.8.3
aiosignal                          1.2.0
alabaster                          0.7.12
anaconda-client                    1.11.0
anaconda-navigator                 2.1.2
anaconda-project                   0.11.1
anyio                              3.5.0
appdirs                            1.4.4
applaunchservices                  0.3.0
appnope                            0.1.2
appscript                          1.1.2
argh                               0.26.2
argon2-cffi                        21.3.0
argon2-cffi-bindings               21.2.0
arrow                              1.2.3
asgiref                            3.6.0
asn1crypto                         1.4.0
astroid                            2.11.7
astropy                            5.1
asttokens                          2.0.5
astunparse                         1.6.3
async-generator                    1.10
async-timeout                      4.0.2
atomicwrites                       1.4.0
attr                               0.3.1
attrs                              22.1.0
Automat                            20.2.0
autopep8                           1.6.0
awswrangler                        3.5.2
azure-core                         1.26.4
azure-storage-blob                 12.16.0
Babel                              2.11.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.11.1
binaryornot                        0.4.4
bitarray                           2.5.1
bkcharts                           0.2
black                              22.6.0
bleach                             5.0.1
blinker                            1.4
blis                               0.7.9
bokeh                              2.4.3
boto                               2.49.0
boto3                              1.34.36
botocore                           1.34.36
Bottleneck                         1.3.5
boxing                             0.1.4
brotlipy                           0.7.0
cached-property                    1.5.2
cachetools                         4.2.2
catalogue                          2.0.8
certifi                            2022.12.7
cffi                               1.15.1
chardet                            4.0.0
charset-normalizer                 2.0.4
click                              8.0.4
cloudpickle                        2.0.0
clyent                             1.2.2
colorama                           0.4.6
colorcet                           3.0.1
comm                               0.1.2
conda                              23.1.0
conda-build                        3.23.3
conda-content-trust                0.1.3
conda-pack                         0.6.0
conda-package-handling             2.0.2
conda_package_streaming            0.7.0
conda-repo-cli                     1.0.27
conda-token                        0.4.0
conda-verify                       3.4.2
confection                         0.0.3
constantly                         15.1.0
contextlib2                        0.6.0.post1
contourpy                          1.0.5
cookiecutter                       1.7.3
coreapi                            2.3.3
coreschema                         0.0.4
cryptography                       38.0.4
cssselect                          1.1.0
cycler                             0.11.0
cymem                              2.0.7
Cython                             0.29.32
cytoolz                            0.12.0
daal4py                            2021.3.0
dask                               2022.2.1
datashader                         0.14.4
datashape                          0.5.4
datatable                          1.0.0
debugpy                            1.5.1
decorator                          5.1.1
defusedxml                         0.7.1
diff-match-patch                   20200713
dill                               0.3.6
distributed                        2022.2.1
Django                             3.2.16
django-annoying                    0.10.6
django-cors-headers                3.6.0
django-debug-toolbar               3.2.1
django-extensions                  3.1.0
django-filter                      2.4.0
django-model-utils                 4.1.1
django-ranged-fileresponse         0.1.2
django-rest-swagger                2.2.0
django-rq                          2.5.1
django-storages                    1.12.3
django-user-agents                 0.4.0
djangorestframework                3.13.1
docker-pycreds                     0.4.0
docutils                           0.18.1
drf-dynamic-fields                 0.3.0
drf-flex-fields                    0.9.5
drf-generators                     0.3.0
drf-yasg                           1.20.0
EMD-signal                         1.4.0
entrypoints                        0.4
et-xmlfile                         1.1.0
executing                          0.8.3
expiringdict                       1.2.2
fastcache                          1.1.0
fastjsonschema                     2.16.2
filelock                           3.9.0
flake8                             4.0.1
Flask                              1.1.2
flatbuffers                        1.12
flit_core                          3.6.0
fonttools                          4.25.0
frozenlist                         1.3.3
fsspec                             2022.11.0
future                             0.18.2
gast                               0.4.0
gensim                             4.3.0
geographiclib                      1.52
geopy                              2.2.0
gevent                             22.10.2
gitdb                              4.0.9
GitPython                          3.1.27
glob2                              0.7
gmpy2                              2.1.2
google-api-core                    2.10.0
google-auth                        2.11.0
google-auth-oauthlib               0.4.4
google-cloud-appengine-logging     1.1.0
google-cloud-audit-log             0.2.0
google-cloud-core                  2.3.2
google-cloud-logging               2.7.2
google-cloud-storage               2.5.0
google-crc32c                      1.5.0
google-pasta                       0.2.0
google-resumable-media             2.3.3
googleapis-common-protos           1.56.4
graphviz                           0.20
greenlet                           2.0.1
grpc-google-iam-v1                 0.12.3
grpcio                             1.42.0
grpcio-status                      1.48.2
h5py                               3.7.0
HeapDict                           1.0.1
holoviews                          1.15.4
html5lib                           1.1
htmlmin                            0.1.12
hvplot                             0.8.2
hyperlink                          21.0.0
idna                               3.4
imagecodecs                        2021.8.26
imageio                            2.19.3
imagesize                          1.4.1
imbalanced-learn                   0.9.1
imblearn                           0.0
importlib-metadata                 4.11.3
imutils                            0.5.4
incremental                        21.3.0
inflection                         0.5.1
iniconfig                          1.1.1
install                            1.3.5
intake                             0.6.6
intervaltree                       3.1.0
ipykernel                          6.19.2
ipython                            7.31.1
ipython-genutils                   0.2.0
ipywidgets                         7.6.5
isodate                            0.6.1
isort                              5.9.3
itemadapter                        0.3.0
itemloaders                        1.0.4
itsdangerous                       2.0.1
itypes                             1.2.0
jdcal                              1.4.1
jedi                               0.18.1
jellyfish                          0.9.0
Jinja2                             3.1.2
jinja2-time                        0.2.0
jmespath                           0.10.0
joblib                             1.1.1
json5                              0.9.6
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter_client                     7.4.9
jupyter-console                    6.4.4
jupyter_core                       5.2.0
jupyter-server                     1.23.4
jupyterlab                         3.5.3
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.10.3
jupyterlab-widgets                 1.0.0
keras                              2.10.0
Keras-Preprocessing                1.1.2
keyring                            23.4.0
kiwisolver                         1.4.4
label-studio                       1.7.3
label-studio-converter             0.0.51
label-studio-tools                 0.0.2
langcodes                          3.3.0
launchdarkly-server-sdk            7.5.0
lazy_loader                        0.1rc2
lazy-object-proxy                  1.6.0
libarchive-c                       2.9
libclang                           14.0.1
lightgbm                           4.0.0
littleutils                        0.2.2
llvmlite                           0.39.1
locket                             1.0.0
lockfile                           0.12.2
lxml                               4.9.1
Markdown                           3.3.7
MarkupSafe                         2.0.1
marshmallow                        3.19.0
matplotlib                         3.6.2
matplotlib-inline                  0.1.6
mccabe                             0.7.0
mistune                            0.8.4
mizani                             0.9.3
mkl-fft                            1.3.1
mkl-random                         1.2.2
mkl-service                        2.4.0
mock                               4.0.3
more-itertools                     8.12.0
mpmath                             1.2.1
msgpack                            1.0.3
multidict                          6.0.2
multipledispatch                   0.6.0
multiprocess                       0.70.14
multitasking                       0.0.10
munkres                            1.1.4
murmurhash                         1.0.9
mypy-extensions                    0.4.3
navigator-updater                  0.2.1
nbclassic                          0.4.8
nbclient                           0.5.13
nbconvert                          6.4.4
nbformat                           5.7.0
nest-asyncio                       1.5.6
networkx                           2.8.4
nltk                               3.6.7
nose                               1.3.7
notebook                           6.5.2
notebook_shim                      0.2.2
numba                              0.56.4
numexpr                            2.8.4
numpy                              1.25.2
numpydoc                           1.5.0
oauthlib                           3.2.0
olefile                            0.46
openapi-codec                      1.3.2
opencv-python                      4.6.0.66
openpyxl                           3.0.10
opt-einsum                         3.3.0
ordered-set                        4.0.2
ordereddict                        1.1
outdated                           0.2.1
packaging                          22.0
pandas                             2.1.0
pandas-datareader                  0.10.0
pandas-flavor                      0.3.0
pandocfilters                      1.5.0
panel                              0.14.3
param                              1.12.3
parsel                             1.6.0
parso                              0.8.3
partd                              1.2.0
path                               16.0.0
pathlib                            1.0.1
pathlib2                           2.3.6
pathos                             0.3.0
pathspec                           0.10.3
pathtools                          0.1.2
pathy                              0.6.2
patsy                              0.5.3
pdf2text                           1.0.0
pdfminer                           20191125
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             9.3.0
pingouin                           0.5.2
pip                                24.1
pkginfo                            1.8.3
platformdirs                       2.5.2
plotly                             5.9.0
plotnine                           0.12.2
pluggy                             1.0.0
ply                                3.11
pmdarima                           2.0.2
pox                                0.3.2
poyo                               0.5.0
ppft                               1.7.6.6
preshed                            3.0.8
prometheus-client                  0.14.1
promise                            2.3
prompt-toolkit                     3.0.36
Protego                            0.1.16
proto-plus                         1.22.2
protobuf                           3.19.4
psutil                             5.9.0
psycopg2-binary                    2.9.6
ptyprocess                         0.7.0
pure-eval                          0.2.2
py                                 1.11.0
pyarrow                            15.0.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.8.0

pycosat                            0.6.4
pycparser                          2.21
pycryptodome                       3.18.0
pyct                               0.5.0
pycurl                             7.45.1
pydantic                           1.10.2
PyDispatcher                       2.0.5
pydocstyle                         6.3.0
pyemd                              0.5.1
pyerfa                             2.0.0
pyflakes                           2.4.0
Pygments                           2.11.2
PyHamcrest                         2.0.2
PyJWT                              2.4.0
pylint                             2.14.5
pyls-spyder                        0.4.0
pyobjc-core                        8.5
pyobjc-framework-Cocoa             8.5
pyobjc-framework-CoreServices      8.5
pyobjc-framework-FSEvents          8.5
pyodbc                             4.0.34
pyOpenSSL                          22.0.0
pyparsing                          3.0.9
PyPDF2                             3.0.1
pypdfium2                          3.20.1
PyQt5-sip                          12.11.0
pyreadr                            0.4.6
pyRFC3339                          1.1
pyrsistent                         0.18.0
PySocks                            1.7.1
pytest                             7.1.2
python-dateutil                    2.8.2
python-json-logger                 2.0.4
python-lsp-black                   1.2.1
python-lsp-jsonrpc                 1.0.0
python-lsp-server                  1.5.0
python-slugify                     5.0.2
python-snappy                      0.6.1
python-xbrl                        1.1.1
pytz                               2023.3
pytz-deprecation-shim              0.1.0.post0
pyviz-comms                        2.0.2
PyWavelets                         1.4.1
PyYAML                             6.0
pyzmq                              23.2.0
QDarkStyle                         3.0.2
qstylizer                          0.2.2
QtAwesome                          1.2.2
qtconsole                          5.3.2
QtPy                               2.2.0
queuelib                           1.5.0
redis                              4.5.5
regex                              2022.7.9
requests                           2.28.0
requests-file                      1.5.1
requests-oauthlib                  1.3.0
rope                               0.22.0
rpy2                               3.5.2
rq                                 1.10.1
rsa                                4.7.2
Rtree                              1.0.1
ruamel.yaml                        0.17.21
ruamel.yaml.clib                   0.2.6
ruamel-yaml-conda                  0.17.21
rules                              2.2
s3transfer                         0.10.0
scikit-image                       0.19.3
scikit-learn                       1.0.2
scikit-learn-intelex               2021.20210714.100439
scipy                              1.11.2
Scrapy                             2.6.2
seaborn                            0.12.2
semver                             2.13.0
Send2Trash                         1.8.0
sentry-sdk                         1.6.0
service-identity                   18.1.0
setproctitle                       1.2.3
setuptools                         65.6.3
shap                               0.41.0
shortuuid                          1.0.9
simplegeneric                      0.8.1
simplejson                         3.19.1
singledispatch                     3.7.0
sip                                6.6.2
six                                1.16.0
slicer                             0.0.7
smart-open                         5.2.1
smmap                              5.0.0
sniffio                            1.2.0
snowballstemmer                    2.2.0
sortedcollections                  2.1.0
sortedcontainers                   2.4.0
soupsieve                          2.3.2.post1
spacy                              3.4.2
spacy-legacy                       3.0.10
spacy-loggers                      1.0.3
Sphinx                             5.0.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             2.0.0
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.5
sphinxcontrib-websupport           1.2.4
spyder                             5.3.3
spyder-kernels                     2.3.3
SQLAlchemy                         1.4.39
sqlparse                           0.4.4
srsly                              2.4.5
stack-data                         0.2.0
statsmodels                        0.14.0
sympy                              1.11.1
tables                             3.7.0
tabulate                           0.8.10
TBB                                0.2
tblib                              1.7.0
tenacity                           8.0.1
tensorboard                        2.10.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.6.0
tensorflow                         2.10.0
tensorflow-estimator               2.10.0
tensorflow-io-gcs-filesystem       0.26.0
termcolor                          1.1.0
terminado                          0.17.1
testpath                           0.6.0
text-unidecode                     1.3
textdistance                       4.2.1
thinc                              8.1.5
threadpoolctl                      2.2.0
three-merge                        0.1.1
tifffile                           2021.7.2
tinycss                            0.4
tinycss2                           1.2.1
tldextract                         3.2.0
toml                               0.10.2
tomli                              2.0.1
tomlkit                            0.11.1
toolz                              0.12.0
torch                              1.12.0
torchaudio                         0.12.0
torchvision                        0.13.0
torchviz                           0.0.2
tornado                            6.2
tqdm                               4.64.1
traitlets                          5.7.1
Twisted                            22.2.0
typed-ast                          1.4.3
typer                              0.4.2
typing_extensions                  4.4.0
tzdata                             2022.1
tzlocal                            4.2
ua-parser                          0.16.1
ujson                              5.4.0
unicodecsv                         0.14.1
Unidecode                          1.2.0
uritemplate                        4.1.1
urllib3                            1.26.14
user-agents                        2.2.0
w3lib                              1.21.0
wandb                              0.12.19
wasabi                             0.10.1
watchdog                           2.1.6
wcwidth                            0.2.5
webencodings                       0.5.1
websocket-client                   0.58.0
Werkzeug                           2.0.3
whatthepatch                       1.0.2
wheel                              0.35.1
whichcraft                         0.6.1
widgetsnbextension                 3.5.2
wrapt                              1.14.1
wurlitzer                          3.0.2
xarray                             2022.11.0
xgboost                            1.6.1
xlrd                               2.0.1
XlsxWriter                         3.0.3
xlwings                            0.27.15
xlwt                               1.3.0
xmljson                            0.2.0
yapf                               0.31.0
yarl                               1.8.1
yfinance                           0.1.70
zict                               2.1.0
zipp                               3.11.0
zope.event                         4.5.0
zope.interface                     5.4.0
zstandard                          0.18.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip show pandas

Name: pandas
Version: 2.1.0
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

        Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
        All rights reserved.

        Copyright (c) 2011-2023, Open source contributors.

        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:

        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.

        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
          and/or other materials provided with the distribution.

        * Neither the name of the copyright holder nor the names of its
          contributors may be used to endorse or promote products derived from
          this software without specific prior written permission.

        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
        AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
        FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
        SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
        CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
        OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: /Users/francomansilla/opt/anaconda3/lib/python3.9/site-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by: awswrangler, datashader, holoviews, hvplot, label-studio, label-studio-converter, mizani, pandas-datareader, pandas-flavor, pingouin, plotnine, pmdarima, pyreadr, seaborn, shap, statsmodels, xarray, yfinance
Note: you may need to restart the kernel to use updated packages.

## 2. Pandas

[Pandas](https://pandas.pydata.org/about/index.html) es una librería que proporciona estructuras de datos y herramientas de análisis de datos de alto rendimiento y fáciles de usar. 
* La estructura de datos principal es el DataFrame, que puede considerarse como una tabla 2D en memoria (como una hoja de cálculo, con nombres de columna y etiquetas de fila). 
* Muchas funciones disponibles en Excel están disponibles mediante programación, como crear tablas dinámicas, calcular columnas basadas en otras columnas, trazar gráficos, etc.
* Proporciona un alto rendimiento para manipular (unir, dividir, modificar…) grandes conjuntos de datos

In [5]:
import pandas as pd

La librería Pandas, de manera genérica, contiene las siguientes **estructuras de datos**:
* **Series**: Array de una dimensión
* **DataFrame**: Se corresponde con una tabla de 2 dimensiones
* **Panel**: Similar a un diccionario de DataFrames

In [6]:
# Creacion de un objeto Series
s = pd.Series([2, 4, 6, 8, 10])
print(s)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [7]:
# Creación de un objeto Series inicializándolo con un diccionario de Python
altura = {"Santiago": 187, "Pedro": 178, "Julia": 170, "Ana": 165}
s = pd.Series(altura)
print(s)

Santiago    187
Pedro       178
Julia       170
Ana         165
dtype: int64

In [8]:
# Creación de un DataFrame inicializándolo con un diccionario de objetios Series
personas = {
    "peso": pd.Series([84, 90, 56, 64], ["Santiago","Pedro", "Ana", "Julia"]),
    "altura": pd.Series({"Santiago": 187, "Pedro": 178, "Julia": 170, "Ana": 165}),
    "hijos": pd.Series([2, 3], ["Pedro", "Julia"])
}

df = pd.DataFrame(personas)
df

          peso  altura  hijos
Ana         56     165    NaN
Julia       64     170    3.0
Pedro       90     178    2.0
Santiago    84     187    NaN

* Acceder elementos del dataframe

In [9]:
df["peso"]

Ana         56
Julia       64
Pedro       90
Santiago    84
Name: peso, dtype: int64

In [10]:
df[["peso", "altura"]]

          peso  altura
Ana         56     165
Julia       64     170
Pedro       90     178
Santiago    84     187

In [11]:
# Pueden combinarse los metodos anteriores con expresiones booleanas
df[df["peso"] > 80]

          peso  altura  hijos
Pedro       90     178    2.0
Santiago    84     187    NaN

In [12]:
# Pueden combinarse los metodos anteriores con expresiones booleanas
df[(df["peso"] > 80) & (df["altura"] > 180)]

          peso  altura  hijos
Santiago    84     187    NaN

### 2.1. Cargas de Base de Datos externos

[Read de Pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) Estas funciones hacen de Pandas una herramienta extremadamente versátil para la carga y manipulación de diversos formatos de datos, permitiendo a los usuarios trabajar con una amplia variedad de fuentes de datos en análisis de datos y ciencia de datos.

1. **CSV** (`read_csv`): Lee archivos delimitados por comas (CSV) o separados por otros delimitadores, que son comunes en datos tabulares.

2. **Excel** (`read_excel`): Lee datos de archivos Excel (`.xls`, `.xlsx`), utilizando internamente paquetes como `xlrd`, `openpyxl` o `odf`.

3. **HDF5** (`read_hdf`): Lee archivos HDF5, que son formatos ideales para almacenar grandes cantidades de datos científicos.

4. **SQL** (`read_sql`): Lee datos directamente de bases de datos SQL utilizando sentencias SQL, haciendo uso de SQLAlchemy o una conexión directa a la base de datos.

5. **JSON** (`read_json`): Lee datos desde un string JSON, transformándolos directamente en un DataFrame.

6. **HTML** (`read_html`): Extrae tablas de archivos HTML, lo cual es útil para scraping de datos de páginas web.

7. **Feather** (`read_feather`): Lee archivos en formato Feather, un formato de archivo binario rápido diseñado para la interoperabilidad entre DataFrame de Python y R.

8. **Parquet** (`read_parquet`): Lee archivos en formato Parquet, que es un formato de almacenamiento en columnas optimizado para el trabajo con grandes volúmenes de datos.

9. **Msgpack** (`read_msgpack`)(Deprecated): Anteriormente se utilizaba para leer datos en el formato de serialización de Msgpack, pero ha sido deprecado desde la versión 1.0.0.

10. **Stata** (`read_stata`): Lee datos de archivos de Stata (.dta), utilizados comúnmente en investigaciones económicas y sociales.

11. **SAS** (`read_sas`): Lee datos de archivos de SAS (.sas7bdat y .xpt) que son utilizados en análisis estadístico avanzado.

12. **SPSS** (`read_spss`): Lee archivos de SPSS (.sav), un software ampliamente utilizado en la investigación social.

13. **Google BigQuery** (`read_gbq`): Extrae datos desde Google BigQuery, un servicio de almacenamiento de datos grande en la nube.

14. **Clipboard** (`read_clipboard`): Captura contenido de tu portapapeles y lo convierte en un DataFrame, útil para copiar y pegar datos directamente en Python.

15. **ORC** (`read_orc`): Lee archivos ORC (Optimized Row Columnar), que son utilizados en sistemas como Hadoop para un almacenaje eficiente de datos en columnas.

* Definición de directorio de trabajo

In [13]:
dir = "/Users/francomansilla/Library/CloudStorage/GoogleDrive-franco.andres.mansilla@gmail.com/Mi unidad/universidad mayor/Aplicaciones Computacionales/Clase 6"

* Importar Base de Datos externo

In [14]:
# Forma 1

file_path = dir + "/base de datos autos.xls"

# Leer el archivo Excel
df = pd.read_excel(file_path)

In [15]:
# Forma 2
df = pd.read_excel(dir+"/base de datos autos.xls")

### 2.2. Detalles del Dataframe

In [16]:
# primeras 5 filas
df.head()

            make  price  mpg  rep78  weight  length   foreign
0    AMC Concord   4099   22    3.0    2930     186  Domestic
1      AMC Pacer   4749   17    3.0    3350     173  Domestic
2     AMC Spirit   3799   22    NaN    2640     168  Domestic
3  Buick Century   4816   20    3.0    3250     196  Domestic
4  Buick Electra   7827   15    4.0    4080     222  Domestic

In [17]:
# últimas 5 filas
df.tail()

           make  price  mpg  rep78  weight  length  foreign
69    VW Dasher   7140   23    4.0    2160     172  Foreign
70    VW Diesel   5397   41    5.0    2040     155  Foreign
71    VW Rabbit   4697   25    4.0    1930     155  Foreign
72  VW Scirocco   6850   25    4.0    1990     156  Foreign
73    Volvo 260  11995   17    5.0    3170     193  Foreign

In [18]:
# Nombres de campos Dataframe
df.columns

Index(['make', 'price', 'mpg', 'rep78', 'weight', 'length', 'foreign'], dtype='object')

In [19]:
# Dimensión del Dataframe
print("Cantidad de Columnas:", len(df.columns))
print("Cantidad de Observaciones:", len(df))
print("Dimensión del dataframe:", df.shape)

Cantidad de Columnas: 7
Cantidad de Observaciones: 74
Dimensión del dataframe: (74, 7)

In [20]:
# Formatos del Dataframe
print("Formato de los campos:", df.dtypes)

Formato de los campos: make        object
price        int64
mpg          int64
rep78      float64
weight       int64
length       int64
foreign     object
dtype: object

In [21]:
# Información del Dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   make     74 non-null     object
 1   price    74 non-null     int64
 2   mpg      74 non-null     int64
 3   rep78    69 non-null     float64
 4   weight   74 non-null     int64
 5   length   74 non-null     int64
 6   foreign  74 non-null     object
dtypes: float64(1), int64(4), object(2)
memory usage: 4.2+ KB

* Memoria ocupada

In [22]:
print("Memoria utilizada por campo: ", df.memory_usage())

Memoria utilizada por campo:  Index      128
make       592
price      592
mpg        592
rep78      592
weight     592
length     592
foreign    592
dtype: int64

In [23]:
print("Memoria utilizada por dataframe: ", df.memory_usage().sum())

Memoria utilizada por dataframe:  4272

### 2.3. Acceder a observaciones del dataframe

In [24]:
# Acceder una fila
df.iloc[0]

make       AMC Concord
price             4099
mpg                 22
rep78              3.0
weight            2930
length             186
foreign       Domestic
Name: 0, dtype: object

In [25]:
# Acceder grupo de fila
df.iloc[0:3]

          make  price  mpg  rep78  weight  length   foreign
0  AMC Concord   4099   22    3.0    2930     186  Domestic
1    AMC Pacer   4749   17    3.0    3350     173  Domestic
2   AMC Spirit   3799   22    NaN    2640     168  Domestic

In [26]:
# Acceder grupo de fila con una columna
df.iloc[0:3, 0]

0    AMC Concord
1      AMC Pacer
2     AMC Spirit
Name: make, dtype: object

In [27]:
# Acceder grupo de fila con un grupo de columna
df.iloc[0:3, 0:3]

          make  price  mpg
0  AMC Concord   4099   22
1    AMC Pacer   4749   17
2   AMC Spirit   3799   22

In [28]:
# Acceder con nombres de columnas
df.loc[0:3, ["make", "price", "mpg"]]

            make  price  mpg
0    AMC Concord   4099   22
1      AMC Pacer   4749   17
2     AMC Spirit   3799   22
3  Buick Century   4816   20

In [29]:
df_copy = df.copy()
df_copy.head()

            make  price  mpg  rep78  weight  length   foreign
0    AMC Concord   4099   22    3.0    2930     186  Domestic
1      AMC Pacer   4749   17    3.0    3350     173  Domestic
2     AMC Spirit   3799   22    NaN    2640     168  Domestic
3  Buick Century   4816   20    3.0    3250     196  Domestic
4  Buick Electra   7827   15    4.0    4080     222  Domestic

* Borrar columnas: Forma 1

In [30]:
df_copy = df_copy.drop(["make", "price"], axis = 1)
df_copy.head()

   mpg  rep78  weight  length   foreign
0   22    3.0    2930     186  Domestic
1   17    3.0    3350     173  Domestic
2   22    NaN    2640     168  Domestic
3   20    3.0    3250     196  Domestic
4   15    4.0    4080     222  Domestic

* Borrar columnas: Forma 2

In [31]:
df_copy = df.copy()
df_copy.drop(["make", "price"], axis = 1, inplace = True)
df_copy.head()

   mpg  rep78  weight  length   foreign
0   22    3.0    2930     186  Domestic
1   17    3.0    3350     173  Domestic
2   22    NaN    2640     168  Domestic
3   20    3.0    3250     196  Domestic
4   15    4.0    4080     222  Domestic

* Medidas Estadísticas

In [32]:
print("Media de precio es:", df[['price']].mean())
print("Desviación Estandar de precio es:", df['price'].std())

Media de precio es: price    6165.256757
dtype: float64
Desviación Estandar de precio es: 2949.4958847689186

### 2.4. Funciones personalizadas sobre Dataframe

* Función personalizada para estadística

In [33]:
# Función para calcular la media y desviación estándar de una columna específica

def mean_and_sd(column_name):
    
    media = df[column_name].mean()
    sd = df[column_name].std()
    
    return media, sd

In [34]:
# Llama a la función pasando el nombre de la columna 'price' como string
media_precio, sd_precio = mean_and_sd('price')

# Imprime los resultados
print("Media del precio:", media_precio)
print("Desviación estándar del precio:", sd_precio)

Media del precio: 6165.256756756757
Desviación estándar del precio: 2949.4958847689186

* Función personalizada por observación

In [35]:
# Aplicar una función externa a una columna del DataFrame
def func(x):
    return x * 980

In [36]:
df['new_price_clp'] = df["price"].apply(func)
df[['price', 'new_price_clp']]

    price  new_price_clp
0    4099        4017020
1    4749        4654020
2    3799        3723020
3    4816        4719680
4    7827        7670460
..    ...            ...
69   7140        6997200
70   5397        5289060
71   4697        4603060
72   6850        6713000
73  11995       11755100

[74 rows x 2 columns]

In [37]:
# Usando función lambda
# Aplicar una función lambda directamente con apply para crear una nueva columna
df['new_price_clp_2'] = df['price'].apply(lambda x: x * 980)

# Mostrar las columnas 'price' y 'new_price_clp' para ver el resultado
df[['price', 'new_price_clp']]

    price  new_price_clp
0    4099        4017020
1    4749        4654020
2    3799        3723020
3    4816        4719680
4    7827        7670460
..    ...            ...
69   7140        6997200
70   5397        5289060
71   4697        4603060
72   6850        6713000
73  11995       11755100

[74 rows x 2 columns]

# Exportar Dataframe

Pandas también proporciona varias funciones para exportar DataFrames a diferentes formatos de archivos, lo que permite una fácil distribución y almacenamiento de datos. Te muestro una lista de las principales funciones de exportación (`to_...`) disponibles en Pandas, con una breve descripción de cada una:

1. **CSV** (`to_csv`): Exporta un DataFrame a un archivo delimitado por comas (CSV) o por otro delimitador especificado, lo cual es útil para compatibilidad con muchos sistemas.

2. **Excel** (`to_excel`): Escribe un DataFrame a un archivo Excel (`.xls`, `.xlsx`), permitiendo conservar el formato y las características propias de Excel.

3. **HDF5** (`to_hdf`): Guarda un DataFrame en un archivo HDF5, ideal para trabajar con grandes volúmenes de datos y acceso rápido a segmentos específicos de los datos.

4. **JSON** (`to_json`): Convierte un DataFrame en una cadena JSON, facilitando la integración con aplicaciones web y APIs que consumen este formato.

5. **HTML** (`to_html`): Convierte un DataFrame en una tabla HTML, útil para la visualización en páginas web y reportes basados en HTML.

6. **Markdown** (`to_markdown`): Exporta un DataFrame a formato Markdown, que es ampliamente usado en documentación y plataformas que soportan Markdown, como GitHub.

7. **Feather** (`to_feather`): Escribe un DataFrame a un archivo Feather, proporcionando una alta eficiencia en la lectura y escritura, especialmente útil para la transferencia de datos entre Python y R.

8. **Parquet** (`to_parquet`): Guarda un DataFrame en formato Parquet, optimizado para el almacenamiento en columnas y muy usado en entornos de big data como Hadoop.

9. **Msgpack** (`to_msgpack`)(Deprecated): Anteriormente usado para serializar DataFrames en el formato binario Msgpack, pero ha sido deprecado desde la versión 1.0.0.

10. **Stata** (`to_stata`): Exporta un DataFrame a un archivo de Stata (.dta), común en análisis estadístico en ciencias sociales y económicas.

11. **SAS** (`to_sas`): (No directamente disponible, pero los DataFrames pueden ser convertidos en formatos compatibles con SAS utilizando otros métodos).

12. **SPSS** (`to_spss`): Escribe un DataFrame a un archivo SPSS (.sav), útil en el ámbito de la investigación social.

13. **SQL** (`to_sql`): Guarda un DataFrame en una tabla SQL, utilizando SQLAlchemy o una conexión directa, lo cual es fundamental para integrar análisis de datos con bases de datos.

14. **Clipboard** (`to_clipboard`): Copia un DataFrame al portapapeles, lo que facilita pegar los datos en aplicaciones como Excel o editores de texto.

15. **Pickle** (`to_pickle`): Serializa un DataFrame en formato binario usando pickle, conveniente para almacenamiento temporal o transferencia de objetos Python entre procesos.

16. **Records** (`to_records`): Convierte un DataFrame a un array NumPy estructurado o a un registro, útil para ciertos tipos de manipulaciones numéricas.

17. **Latex** (`to_latex`): Exporta un DataFrame a formato LaTeX, ideal para la creación de documentos científicos y técnicos con alta calidad de tiposet.

In [38]:
df[['price', 'new_price_clp']].to_csv(dir + "/df_price.csv")

In [39]:
df.to_csv(dir + "/all_df.csv")