# **Clase 2.** Expresiones Regulares (Regex) 

**Librerías**

[![re](https://img.shields.io/badge/re-3776AB?style=flat&logo=python&logoColor=white)](https://docs.python.org/3/library/re.html)
[![Pandas](https://img.shields.io/badge/Pandas-150458?style=flat&logo=pandas&logoColor=white)](https://pandas.pydata.org/docs/)

**Técnicas Regex**

[![Grupos de captura](https://img.shields.io/badge/Grupos_de_captura-0078D4?style=flat&logo=python&logoColor=white)](https://docs.python.org/3/library/re.html#re.Match.group)
[![Lookahead](https://img.shields.io/badge/Lookahead_Lookbehind-2E8B57?style=flat&logo=python&logoColor=white)](https://docs.python.org/3/library/re.html#re.compile)
[![Greedy vs Lazy](https://img.shields.io/badge/Greedy_vs_Lazy-E34F26?style=flat&logo=python&logoColor=white)](https://docs.python.org/3/howto/regex.html#greedy-versus-non-greedy)
[![re.VERBOSE](https://img.shields.io/badge/re.VERBOSE-6A0DAD?style=flat&logo=python&logoColor=white)](https://docs.python.org/3/library/re.html#re.VERBOSE)

**Funciones principales**

[![re.findall](https://img.shields.io/badge/re.findall-B8860B?style=flat&logo=python&logoColor=white)](https://docs.python.org/3/library/re.html#re.findall)
[![re.sub](https://img.shields.io/badge/re.sub-228B22?style=flat&logo=python&logoColor=white)](https://docs.python.org/3/library/re.html#re.sub)
[![re.compile](https://img.shields.io/badge/re.compile-C0392B?style=flat&logo=python&logoColor=white)](https://docs.python.org/3/library/re.html#re.compile)

---

**Regex** (expresión regular) es un patrón que describe un conjunto de cadenas de texto. Se puede usar para buscar, extraer o reemplazar texto en Python y otros lenguajes de programación. Es una herramienta muy poderosa para procesar texto no estructurado, como logs, tickets de soporte, transacciones bancarias, etc. Se diferencia de los métodos tradicionales de búsqueda de texto porque permite definir patrones complejos y flexibles, en lugar de buscar coincidencias exactas.

## 1. Metacaracteres esenciales

| Símbolo | Significado | Ejemplo |
|---------|-------------|--------|
| `.`     | Cualquier carácter (excepto newline) | `a.c` → "abc", "a1c" |
| `^`     | Inicio de cadena | `^Hola` |
| `$`     | Fin de cadena | `mundo$` |
| `*`     | 0 o más repeticiones | `ab*` → "a", "ab", "abb" |
| `+`     | 1 o más repeticiones | `ab+` → "ab", "abb" |
| `?`     | 0 o 1 (opcional) | `colou?r` → "color", "colour" |
| `{n,m}` | Entre n y m repeticiones | `a{2,4}` |
| `[]`    | Clase de caracteres | `[aeiou]` |
| `\|`    | OR lógico | `gato\|perro` |
| `()`    | Grupo de captura | `(ab)+` |
| `\`     | Escapa un metacarácter | `\.` = punto literal |

## 2. Secuencias especiales

| Secuencia | Significado |
|-----------|-------------|
| `\d`  | Dígito `[0-9]` |
| `\D`  | No dígito |
| `\w`  | Carácter de palabra `[a-zA-Z0-9_]` |
| `\W`  | No carácter de palabra |
| `\s`  | Espacio en blanco |
| `\S`  | No espacio en blanco |
| `\b`  | Límite de palabra |
| `\B`  | No límite de palabra |

---

In [28]:
import re
import pandas as pd

pd.set_option('display.max_colwidth', 60)

# **1. Ejemplo**

Este ejercicio tiene le proposito de mostrar el paso a paso de cómo construir un regex para extraer información de un texto no estructurado. El objetivo es extraer la cantidad, el producto y el precio de cada línea de texto.

In [18]:
texto = """
2x Manzanas Fuji ......... $1.990
3 kg DE TOMATE (RED) -> $2.450/kg
1   Pan_Integral [500g]  ... CLP$1.200
- 6un Huevos!! ($150 c/u)
*Leche-Entera* 1L $890.-
4,5 Kg Papas blancas ~$1.300 c/kilo
1xPaquete: Fideos #200gr $640
2  Botellas   Aceite (1L) ... $3.200 ea.
1/2 Sandía -> $1.500
10 [Yogurt] Natural 150ML $250c/u
N° items: 3 || Detergente 3Kg || $4.990
Queso*Gouda*250g==$2.350
1 - Café molido (250 g) ... $3.890
2x Jabón líquido 750ml $1.100/u
~3 Plátanos (kg) — $990
"""

### **Paso 1.** Cantidad

* `\d+` → uno o más dígitos
* `[.,]?` → opcionalmente un punto o coma (para decimales)
* `\d*` → más dígitos después del separador
* `|\d+/\d+` → o, alternativamente, una fracción tipo 1/2

In [20]:
# Paso 1. Cantidad
patron_cantidad = r'(\d+[.,]?\d*|\d+/\d+)'
print(re.findall(patron_cantidad, "4,5 Kg Papas"))

['4,5']

### **Paso 2:** saltar el ruido inicial (símbolos sueltos antes del número)

* `^` → inicio de línea

* `[\s\-\*~]*` → cero o más espacios, guiones, asteriscos o virgulillas

In [ ]:
patron_ruido_inicial = r'^[\s\-\*~]*'
print(re.sub(patron_ruido_inicial, '', "  - 4,5 Kg Papas"))

4,5 Kg Papas

### **Paso 3:** el producto (la parte "sucia" del medio)

* Aquí usamos un grupo no codicioso (`.+?`) porque no sabemos qué hay exactamente, solo que termina antes del precio.
* El `?` después de `.+` es clave: evita que el regex "se coma" hasta el último `$` de la línea.

In [22]:
patron_producto = r'(.+?)'
print(re.findall(patron_producto, "4,5 Kg Papas"))

['4', ',', '5', ' ', 'K', 'g', ' ', 'P', 'a', 'p', 'a', 's']

### **Paso 4:** el precio

* `\$` → el signo peso (escapado porque $ es metacarácter)
* `\s*` → espacios opcionales después
* `([\d.]+)` → dígitos y puntos (para capturar miles tipo 1.990)

* El precio siempre va precedido por `$` (a veces con `CLP` antes):

In [23]:
patron_precio = r'\$\s*([\d.]+)'

print(re.findall(patron_precio, "4,5 Kg Papas $1.300 c/kilo"))

['1.300']

### **Paso 5:** unir todo

⚠️ **Nota**: con `re.VERBOSE` los espacios literales en el patrón se ignoran salvo que los escapes o uses `[ ]`. Como aquí no tengo espacios literales sueltos, está bien, pero es un punto importante para mencionar en clase.

In [24]:
patron_completo = re.compile(
    r'^[\s\-\*~]*'              # ruido inicial
    r'(\d+[.,]?\d*|\d+/\d+)'    # grupo 1: cantidad
    r'.*?'                       # cualquier cosa (unidad, "x", etc.)
    r'(.+?)'                     # grupo 2: producto
    r'\$\s*([\d.]+)',            # grupo 3: precio
    re.VERBOSE
)

In [25]:
filas = []
for linea in texto.strip().splitlines():
    m = patron_completo.search(linea)
    if m:
        cantidad, producto, precio = m.groups()
        # limpieza básica del producto
        producto = re.sub(r'[\*\[\]\(\)\.\-_#~]', ' ', producto)
        producto = re.sub(r'\s+', ' ', producto).strip()
        filas.append((cantidad, producto, precio))
    else:
        filas.append(("???", linea, "???"))  # para mostrar fallos en clase

for f in filas:
    print(f)

('2', 'x Manzanas Fuji', '1.990')
('3', 'kg DE TOMATE RED >', '2.450')
('1', 'Pan Integral 500g CLP', '1.200')
('6', 'un Huevos!!', '150')
('???', '*Leche-Entera* 1L $890.-', '???')
('4,5', 'Kg Papas blancas', '1.300')
('1', 'xPaquete: Fideos 200gr', '640')
('2', 'Botellas Aceite 1L', '3.200')
('1', '/2 Sandía >', '1.500')
('10', 'Yogurt Natural 150ML', '250')
('???', 'N° items: 3 || Detergente 3Kg || $4.990', '???')
('???', 'Queso*Gouda*250g==$2.350', '???')
('1', 'Café molido 250 g', '3.890')
('2', 'x Jabón líquido 750ml', '1.100')
('3', 'Plátanos kg —', '990')

In [26]:
# En tabla:

df = pd.DataFrame(filas, columns=["cantidad", "producto", "precio"])
print(df.to_string(index=False))

cantidad                                producto precio
       2                         x Manzanas Fuji  1.990
       3                      kg DE TOMATE RED >  2.450
       1                   Pan Integral 500g CLP  1.200
       6                             un Huevos!!    150
     ???                *Leche-Entera* 1L $890.-    ???
     4,5                        Kg Papas blancas  1.300
       1                  xPaquete: Fideos 200gr    640
       2                      Botellas Aceite 1L  3.200
       1                             /2 Sandía >  1.500
      10                    Yogurt Natural 150ML    250
     ??? N° items: 3 || Detergente 3Kg || $4.990    ???
     ???                Queso*Gouda*250g==$2.350    ???
       1                       Café molido 250 g  3.890
       2                   x Jabón líquido 750ml  1.100
       3                           Plátanos kg —    990

### **¡Tarea!** Mejore el patrón para que capture correctamente los precios, cantidad y productos de la lista de compras.

---
# **2. Casos** 
**Idea central:** las empresas generan enormes volúmenes de texto semi-estructurado que nadie quiere procesar a mano: tickets de soporte, logs de servidores, transacciones bancarias, reviews de clientes. Regex + Python convierte ese texto en una **tabla analizable** en minutos.

### Estructura del taller

Vamos a ver **3 casos reales**, y en cada uno seguimos la misma progresión:

1. **Encontrar** — filtrar líneas que cumplen un patrón (`re.search`)
2. **Extraer** — capturar campos específicos de un registro (`re.search` con grupos nombrados)
3. **Estructurar** — aplicar el patrón a todo el dataset y construir una tabla con `pandas`, lista para responder una pregunta de negocio

| Caso | Dominio | Pregunta de negocio |
|---|---|---|
| 1 | Tickets de soporte | ¿Cuál es el problema #1 que reportan los clientes? |
| 2 | Transacciones bancarias | ¿Hay cargos duplicados o sospechosos? |
| 3 | Logs de servidor | ¿Qué servidor está fallando más? |

---


## **Caso 1:** Tickets de soporte

Este es el dataset: 20 tickets de soporte, cada uno con metadata (fecha, número, cliente, prioridad, estado) y un asunto en texto libre.

**Detalle importante:** varios tickets describen el mismo problema con palabras distintas. Por ejemplo, "no puedo acceder a mi cuenta", "credenciales inválidas" y "contraseña no funciona" son, en el fondo, el mismo bug. Esto es clave para entender una limitación real de regex: **no entiende sinónimos**, solo patrones de texto literal. Vamos a tener que anticipar las variantes nosotros mismos.

In [1]:
tickets = """
[2026-03-02 09:14] TICKET#10234 | Cliente: Juan Pérez | Prioridad: ALTA | Estado: ABIERTO
Asunto: No puedo acceder a mi cuenta, dice "credenciales inválidas" hace 2 días.

[2026-03-02 10:02] TICKET#10235 | Cliente: María Soto | Prioridad: MEDIA | Estado: ABIERTO
Asunto: La app se cierra sola cuando intento subir una foto de perfil.

[2026-03-02 11:45] TICKET#10236 | Cliente: Pedro Ramírez | Prioridad: BAJA | Estado: CERRADO
Asunto: Pregunta sobre cómo cambiar mi método de pago.

[2026-03-02 13:20] TICKET#10237 | Cliente: Andrea Muñoz | Prioridad: ALTA | Estado: ABIERTO
Asunto: Se me cobró dos veces la suscripción este mes, necesito reembolso urgente.

[2026-03-02 14:05] TICKET#10238 | Cliente: Luis Fernández | Prioridad: MEDIA | Estado: EN_PROCESO
Asunto: El botón de "exportar reporte" no responde en Chrome.

[2026-03-02 15:30] TICKET#10239 | Cliente: Camila Rojas | Prioridad: ALTA | Estado: ABIERTO
Asunto: No puedo acceder a mi cuenta, contraseña no funciona desde ayer.

[2026-03-03 08:12] TICKET#10240 | Cliente: Diego Castro | Prioridad: BAJA | Estado: CERRADO
Asunto: Sugerencia: agregar modo oscuro a la aplicación.

[2026-03-03 09:50] TICKET#10241 | Cliente: Valentina Díaz | Prioridad: MEDIA | Estado: ABIERTO
Asunto: La app se cierra sola al abrir la sección de pagos.

[2026-03-03 10:30] TICKET#10242 | Cliente: Roberto Sánchez | Prioridad: ALTA | Estado: EN_PROCESO
Asunto: Se me cobró un monto que no reconozco, revisar urgente.

[2026-03-03 11:15] TICKET#10243 | Cliente: Francisca Vega | Prioridad: BAJA | Estado: CERRADO
Asunto: ¿Cómo descargo mi historial de compras?

[2026-03-03 12:40] TICKET#10244 | Cliente: Matías Herrera | Prioridad: ALTA | Estado: ABIERTO
Asunto: No puedo acceder a mi cuenta desde el celular, en el computador sí funciona.

[2026-03-03 14:22] TICKET#10245 | Cliente: Javiera Torres | Prioridad: MEDIA | Estado: ABIERTO
Asunto: El botón de "exportar reporte" tampoco responde en Firefox.

[2026-03-04 08:05] TICKET#10246 | Cliente: Sebastián Morales | Prioridad: ALTA | Estado: ABIERTO
Asunto: Reembolso urgente, se me cobró dos veces la suscripción de marzo.

[2026-03-04 09:33] TICKET#10247 | Cliente: Antonia Flores | Prioridad: BAJA | Estado: EN_PROCESO
Asunto: Quiero cambiar mi correo de contacto asociado a la cuenta.

[2026-03-04 10:48] TICKET#10248 | Cliente: Cristóbal Reyes | Prioridad: MEDIA | Estado: ABIERTO
Asunto: La app se cierra sola al intentar exportar un reporte en PDF.

[2026-03-04 13:10] TICKET#10249 | Cliente: Constanza Pizarro | Prioridad: ALTA | Estado: ABIERTO
Asunto: No puedo acceder a mi cuenta, el sistema dice "credenciales inválidas".

[2026-03-04 15:55] TICKET#10250 | Cliente: Ignacio Contreras | Prioridad: BAJA | Estado: CERRADO
Asunto: Sugerencia: que el reporte se pueda exportar también en Excel.

[2026-03-05 08:40] TICKET#10251 | Cliente: Florencia Bravo | Prioridad: ALTA | Estado: EN_PROCESO
Asunto: Se me cobró un cargo duplicado, ya es la segunda vez que pasa.

[2026-03-05 09:58] TICKET#10252 | Cliente: Tomás Espinoza | Prioridad: MEDIA | Estado: ABIERTO
Asunto: El botón de exportar reporte no funciona en Safari tampoco.

[2026-03-05 11:20] TICKET#10253 | Cliente: Josefina Gómez | Prioridad: ALTA | Estado: ABIERTO
Asunto: No puedo acceder a mi cuenta, llevo tres intentos fallidos.
"""

print(tickets.strip().split("\n\n")[0])  # vista previa de un ticket

[2026-03-02 09:14] TICKET#10234 | Cliente: Juan Pérez | Prioridad: ALTA | Estado: ABIERTO
Asunto: No puedo acceder a mi cuenta, dice "credenciales inválidas" hace 2 días.

### **Paso 1.1** — Encontrar: filtrar tickets de prioridad ALTA

Lo más simple que se puede hacer con regex: usar `re.search` para quedarnos solo con las líneas que cumplen un patrón.

In [4]:
for bloque in tickets.strip().split("\n\n"):
    primera_linea = bloque.split("\n")[0]
    if re.search(r'Prioridad: ALTA', primera_linea):
        print(primera_linea)

[2026-03-02 09:14] TICKET#10234 | Cliente: Juan Pérez | Prioridad: ALTA | Estado: ABIERTO
[2026-03-02 13:20] TICKET#10237 | Cliente: Andrea Muñoz | Prioridad: ALTA | Estado: ABIERTO
[2026-03-02 15:30] TICKET#10239 | Cliente: Camila Rojas | Prioridad: ALTA | Estado: ABIERTO
[2026-03-03 10:30] TICKET#10242 | Cliente: Roberto Sánchez | Prioridad: ALTA | Estado: EN_PROCESO
[2026-03-03 12:40] TICKET#10244 | Cliente: Matías Herrera | Prioridad: ALTA | Estado: ABIERTO
[2026-03-04 08:05] TICKET#10246 | Cliente: Sebastián Morales | Prioridad: ALTA | Estado: ABIERTO
[2026-03-04 13:10] TICKET#10249 | Cliente: Constanza Pizarro | Prioridad: ALTA | Estado: ABIERTO
[2026-03-05 08:40] TICKET#10251 | Cliente: Florencia Bravo | Prioridad: ALTA | Estado: EN_PROCESO
[2026-03-05 11:20] TICKET#10253 | Cliente: Josefina Gómez | Prioridad: ALTA | Estado: ABIERTO

### **Paso 1.2** — Extraer: capturar los campos de un ticket

Ahora vamos un nivel más allá: en lugar de solo *encontrar* líneas, queremos *extraer* cada campo (fecha, número, cliente, prioridad, estado, asunto) como datos estructurados.

Para esto usamos **grupos nombrados**: `(?P<nombre>patrón)`. Esto nos permite después llamar `.groupdict()` y obtener un diccionario directamente, en lugar de tener que acordarnos del orden de los grupos.

Construcción del patrón, pieza por pieza:

```
\[(?P<fecha>\d{4}-\d{2}-\d{2}) (?P<hora>\d{2}:\d{2})\]   -> [2026-03-02 09:14]
TICKET#(?P<numero>\d+)                                       -> TICKET#10234
\| Cliente: (?P<cliente>[^|]+)                                -> | Cliente: Juan Pérez
\| Prioridad: (?P<prioridad>\w+)                              -> | Prioridad: ALTA
\| Estado: (?P<estado>\w+)                                    -> | Estado: ABIERTO
Asunto: (?P<asunto>.+)                                         -> Asunto: No puedo acceder...
```

In [5]:
patron_ticket = re.compile(
    r'\[(?P<fecha>\d{4}-\d{2}-\d{2}) (?P<hora>\d{2}:\d{2})\] '
    r'TICKET#(?P<numero>\d+) \| '
    r'Cliente: (?P<cliente>[^|]+) \| '
    r'Prioridad: (?P<prioridad>\w+) \| '
    r'Estado: (?P<estado>\w+)\n'
    r'Asunto: (?P<asunto>.+)'
)

ejemplo = tickets.strip().split("\n\n")[0]
m = patron_ticket.search(ejemplo)
m.groupdict()

{'fecha': '2026-03-02',
 'hora': '09:14',
 'numero': '10234',
 'cliente': 'Juan Pérez',
 'prioridad': 'ALTA',
 'estado': 'ABIERTO',
 'asunto': 'No puedo acceder a mi cuenta, dice "credenciales inválidas" hace 2 días.'}

### **Paso 1.3** — Estructurar: tabla completa + clasificación de problemas

Aplicamos el mismo patrón a los 20 tickets y construimos un DataFrame. Luego, para responder *"¿cuál es el problema #1?"*, definimos un segundo diccionario de patrones — uno por categoría de problema — y clasificamos el campo `asunto` de cada ticket.

Esto es exactamente el punto que mencionamos antes: como las mismas categorías se describen con palabras distintas, cada categoría necesita **varias alternativas dentro del regex** (con `|`).

In [6]:
filas = []
for bloque in tickets.strip().split("\n\n"):
    m = patron_ticket.search(bloque)
    if m:
        d = m.groupdict()
        d['cliente'] = d['cliente'].strip()
        filas.append(d)

df_tickets = pd.DataFrame(filas)
df_tickets[['numero', 'cliente', 'prioridad', 'estado']]

   numero            cliente prioridad      estado
0   10234         Juan Pérez      ALTA     ABIERTO
1   10235         María Soto     MEDIA     ABIERTO
2   10236      Pedro Ramírez      BAJA     CERRADO
3   10237       Andrea Muñoz      ALTA     ABIERTO
4   10238     Luis Fernández     MEDIA  EN_PROCESO
5   10239       Camila Rojas      ALTA     ABIERTO
6   10240       Diego Castro      BAJA     CERRADO
7   10241     Valentina Díaz     MEDIA     ABIERTO
8   10242    Roberto Sánchez      ALTA  EN_PROCESO
9   10243     Francisca Vega      BAJA     CERRADO
10  10244     Matías Herrera      ALTA     ABIERTO
11  10245     Javiera Torres     MEDIA     ABIERTO
12  10246  Sebastián Morales      ALTA     ABIERTO
13  10247     Antonia Flores      BAJA  EN_PROCESO
14  10248    Cristóbal Reyes     MEDIA     ABIERTO
15  10249  Constanza Pizarro      ALTA     ABIERTO
16  10250  Ignacio Contreras      BAJA     CERRADO
17  10251    Florencia Bravo      ALTA  EN_PROCESO
18  10252     Tomás Espinoza     MEDIA     ABIERTO
19  10253     Josefina Gómez      ALTA     ABIERTO

In [7]:
categorias = {
    'acceso_cuenta':    r'acceder.*cuenta|credenciales inv|contrase\u00f1a',
    'cobro_duplicado':  r'cobr[\u00f3o].*dos veces|cargo duplicado|reembolso|monto que no reconozco',
    'app_se_cierra':    r'se cierra sola',
    'exportar_reporte': r'exportar.*reporte|bot\u00f3n de.*exportar',
}

def clasificar(asunto):
    for categoria, patron in categorias.items():
        if re.search(patron, asunto, re.IGNORECASE):
            return categoria
    return 'otro'

df_tickets['categoria'] = df_tickets['asunto'].apply(clasificar)
df_tickets[['numero', 'prioridad', 'categoria']]

   numero prioridad         categoria
0   10234      ALTA     acceso_cuenta
1   10235     MEDIA     app_se_cierra
2   10236      BAJA              otro
3   10237      ALTA   cobro_duplicado
4   10238     MEDIA  exportar_reporte
5   10239      ALTA     acceso_cuenta
6   10240      BAJA              otro
7   10241     MEDIA     app_se_cierra
8   10242      ALTA   cobro_duplicado
9   10243      BAJA              otro
10  10244      ALTA     acceso_cuenta
11  10245     MEDIA  exportar_reporte
12  10246      ALTA   cobro_duplicado
13  10247      BAJA              otro
14  10248     MEDIA     app_se_cierra
15  10249      ALTA     acceso_cuenta
16  10250      BAJA              otro
17  10251      ALTA   cobro_duplicado
18  10252     MEDIA  exportar_reporte
19  10253      ALTA     acceso_cuenta

In [8]:
# La pregunta de negocio: ¿cuál es el problema #1 que reportan los clientes?
df_tickets['categoria'].value_counts()

categoria
acceso_cuenta       5
otro                5
cobro_duplicado     4
app_se_cierra       3
exportar_reporte    3
Name: count, dtype: int64

**Lectura de negocio:** con 20 líneas de texto libre, en segundos sabemos que *"problemas de acceso a cuenta"* es la categoría más reportada. Esa es una conversación directa con el equipo de producto o soporte — no un ejercicio académico.

> **Nota pedagógica:** este enfoque de keywords con regex es rápido y explicable, pero tiene un techo: si un cliente describe el mismo problema con palabras que no anticipamos, no lo vamos a detectar. Para eso existen los enfoques de NLP basados en embeddings o modelos de clasificación entrenados — pero regex sigue siendo la herramienta correcta cuando el vocabulario es predecible y se necesita una solución rápida y transparente.

---
## **Caso 2:** Transacciones bancarias

Mismo patrón mental, distinto dominio: ahora son registros de transacciones de tarjeta. La pregunta de negocio cambia a algo muy relevante en un contexto de riesgo/fraude: **¿hay cargos duplicados o sospechosos?**

In [9]:
transacciones = """
2026-03-01T08:23:11 | TXN-998811 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $45.990 | COMERCIO: Falabella Retail | ESTADO: APROBADA
2026-03-01T09:01:45 | TXN-998812 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $12.500 | COMERCIO: Copec Estacion Centro | ESTADO: APROBADA
2026-03-01T09:15:02 | TXN-998813 | CUENTA:3398-XXXX-XXXX-1102 | CREDITO | $850.000 | COMERCIO: Transferencia Sueldo | ESTADO: APROBADA
2026-03-01T11:42:30 | TXN-998814 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $8.990 | COMERCIO: Netflix.com | ESTADO: APROBADA
2026-03-01T14:05:18 | TXN-998815 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $130.000 | COMERCIO: Farmacias Cruz Verde | ESTADO: RECHAZADA
2026-03-01T15:30:55 | TXN-998816 | CUENTA:3398-XXXX-XXXX-1102 | DEBITO | $25.000 | COMERCIO: Uber *Trip Help.uber.com | ESTADO: APROBADA
2026-03-02T08:10:09 | TXN-998817 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $45.990 | COMERCIO: Falabella Retail | ESTADO: APROBADA
2026-03-02T10:20:33 | TXN-998818 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $4.500 | COMERCIO: Copec Estacion Centro | ESTADO: APROBADA
2026-03-02T12:00:00 | TXN-998819 | CUENTA:3398-XXXX-XXXX-1102 | DEBITO | $310.000 | COMERCIO: Pasaje Latam Airlines | ESTADO: APROBADA
2026-03-02T16:45:21 | TXN-998820 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $8.990 | COMERCIO: Netflix.com | ESTADO: RECHAZADA
2026-03-03T07:55:40 | TXN-998821 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $45.990 | COMERCIO: Falabella Retail | ESTADO: APROBADA
2026-03-03T09:33:12 | TXN-998822 | CUENTA:3398-XXXX-XXXX-1102 | DEBITO | $99.990 | COMERCIO: Spotify Premium Anual | ESTADO: APROBADA
2026-03-03T13:18:05 | TXN-998823 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $130.000 | COMERCIO: Farmacias Cruz Verde | ESTADO: APROBADA
2026-03-03T18:02:47 | TXN-998824 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $25.000 | COMERCIO: Uber *Trip Help.uber.com | ESTADO: APROBADA
2026-03-04T08:30:15 | TXN-998825 | CUENTA:3398-XXXX-XXXX-1102 | DEBITO | $4.500 | COMERCIO: Copec Estacion Centro | ESTADO: APROBADA
"""

print(transacciones.strip().splitlines()[0])  # vista previa

2026-03-01T08:23:11 | TXN-998811 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $45.990 | COMERCIO: Falabella Retail | ESTADO: APROBADA

### **Paso 2.1** — Encontrar: transacciones rechazadas

In [10]:
for linea in transacciones.strip().splitlines():
    if re.search(r'ESTADO: RECHAZADA', linea):
        print(linea)

2026-03-01T14:05:18 | TXN-998815 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $130.000 | COMERCIO: Farmacias Cruz Verde | ESTADO: RECHAZADA
2026-03-02T16:45:21 | TXN-998820 | CUENTA:4521-XXXX-XXXX-7732 | DEBITO | $8.990 | COMERCIO: Netflix.com | ESTADO: RECHAZADA

### **Paso 2.2** — Extraer los campos de una transacción

In [11]:
patron_txn = re.compile(
    r'(?P<timestamp>[\d\-T:]+) \| '
    r'TXN-(?P<id>\d+) \| '
    r'CUENTA:(?P<cuenta>[\d\-X]+) \| '
    r'(?P<tipo>DEBITO|CREDITO) \| '
    r'\$(?P<monto>[\d\.]+) \| '
    r'COMERCIO: (?P<comercio>.+?) \| '
    r'ESTADO: (?P<estado>\w+)'
)

ejemplo = transacciones.strip().splitlines()[0]
m = patron_txn.search(ejemplo)
m.groupdict()

{'timestamp': '2026-03-01T08:23:11',
 'id': '998811',
 'cuenta': '4521-XXXX-XXXX-7732',
 'tipo': 'DEBITO',
 'monto': '45.990',
 'comercio': 'Falabella Retail',
 'estado': 'APROBADA'}

### **Paso 2.3** — Estructurar: detectar cargos duplicados

Convertimos a tabla, normalizamos el monto (quitar puntos de miles y convertir a entero), y agrupamos por cuenta + comercio + monto para encontrar **cargos que se repiten exactamente** — una señal clásica de cobro duplicado o suscripción fantasma.

In [12]:
filas = [m.groupdict() for linea in transacciones.strip().splitlines()
         if (m := patron_txn.search(linea))]

df_txn = pd.DataFrame(filas)
df_txn['monto'] = df_txn['monto'].str.replace('.', '', regex=False).astype(int)
df_txn

,timestamp,id,cuenta,tipo,monto,comercio,estado
0,2026-03-01T08:23:11,998811,4521-XXXX-XXXX-7732,DEBITO,45990,Falabella Retail,APROBADA
1,2026-03-01T09:01:45,998812,4521-XXXX-XXXX-7732,DEBITO,12500,Copec Estacion Centro,APROBADA
2,2026-03-01T09:15:02,998813,3398-XXXX-XXXX-1102,CREDITO,850000,Transferencia Sueldo,APROBADA
3,2026-03-01T11:42:30,998814,4521-XXXX-XXXX-7732,DEBITO,8990,Netflix.com,APROBADA
4,2026-03-01T14:05:18,998815,4521-XXXX-XXXX-7732,DEBITO,130000,Farmacias Cruz Verde,RECHAZADA
5,2026-03-01T15:30:55,998816,3398-XXXX-XXXX-1102,DEBITO,25000,Uber *Trip Help.uber.com,APROBADA
6,2026-03-02T08:10:09,998817,4521-XXXX-XXXX-7732,DEBITO,45990,Falabella Retail,APROBADA
7,2026-03-02T10:20:33,998818,4521-XXXX-XXXX-7732,DEBITO,4500,Copec Estacion Centro,APROBADA
8,2026-03-02T12:00:00,998819,3398-XXXX-XXXX-1102,DEBITO,310000,Pasaje Latam Airlines,APROBADA
9,2026-03-02T16:45:21,998820,4521-XXXX-XXXX-7732,DEBITO,8990,Netflix.com,RECHAZADA
10,2026-03-03T07:55:40,998821,4521-XXXX-XXXX-7732,DEBITO,45990,Falabella Retail,APROBADA
11,2026-03-03T09:33:12,998822,3398-XXXX-XXXX-1102,DEBITO,99990,Spotify Premium Anual,APROBADA
12,2026-03-03T13:18:05,998823,4521-XXXX-XXXX-7732,DEBITO,130000,Farmacias Cruz Verde,APROBADA
13,2026-03-03T18:02:47,998824,4521-XXXX-XXXX-7732,DEBITO,25000,Uber *Trip Help.uber.com,APROBADA
14,2026-03-04T08:30:15,998825,3398-XXXX-XXXX-1102,DEBITO,4500,Copec Estacion Centro,APROBADA

In [13]:
# Pregunta de negocio: ¿qué cargos se repiten exactamente (mismo monto, mismo comercio, misma cuenta)?
duplicados = (
    df_txn.groupby(['cuenta', 'comercio', 'monto'])
    .size()
    .reset_index(name='veces')
)
duplicados[duplicados['veces'] > 1]

                cuenta              comercio   monto  veces
7  4521-XXXX-XXXX-7732      Falabella Retail   45990      3
8  4521-XXXX-XXXX-7732  Farmacias Cruz Verde  130000      2
9  4521-XXXX-XXXX-7732           Netflix.com    8990      2

**Lectura de negocio:** vemos que el cargo de Netflix y la suscripción de streaming aparecen mes a mes (esperado), pero también que "Falabella Retail" se repite con el *mismo monto exacto* tres veces — vale la pena revisar si es una compra recurrente legítima o un cargo automático que no debería estar duplicándose.

---
## **Caso 3:** Logs de servidor

Tercer dominio, mismo patrón mental — esta vez para mostrar que la progresión "encontrar → extraer → estructurar" es prácticamente universal frente a texto semi-estructurado.

In [14]:
logs = """
2026-03-05 03:12:01 [INFO] server-01 - Request GET /api/usuarios completed in 120ms - status=200
2026-03-05 03:12:45 [ERROR] server-02 - Database connection timeout after 5000ms - status=503
2026-03-05 03:13:02 [INFO] server-01 - Request POST /api/login completed in 89ms - status=200
2026-03-05 03:13:15 [WARN] server-01 - Memory usage at 87% threshold - status=200
2026-03-05 03:14:00 [ERROR] server-03 - Database connection timeout after 5000ms - status=503
2026-03-05 03:14:22 [INFO] server-02 - Request GET /api/productos completed in 340ms - status=200
2026-03-05 03:15:01 [ERROR] server-01 - Null pointer exception in PaymentService - status=500
2026-03-05 03:15:30 [INFO] server-03 - Request GET /api/usuarios completed in 95ms - status=200
2026-03-05 03:16:10 [ERROR] server-02 - Database connection timeout after 5000ms - status=503
2026-03-05 03:16:45 [WARN] server-01 - Memory usage at 91% threshold - status=200
2026-03-05 03:17:20 [ERROR] server-03 - Null pointer exception in PaymentService - status=500
2026-03-05 03:18:00 [INFO] server-01 - Request POST /api/checkout completed in 210ms - status=200
2026-03-05 03:18:33 [ERROR] server-02 - Database connection timeout after 5000ms - status=503
"""

print(logs.strip().splitlines()[0])  # vista previa

2026-03-05 03:12:01 [INFO] server-01 - Request GET /api/usuarios completed in 120ms - status=200

### **Paso 3.1 a 3.3** — Esta vez en un solo bloque

Como ya vimos la progresión dos veces, aquí la mostramos completa de una vez: extraer todos los campos, construir la tabla, y responder la pregunta de negocio.

In [15]:
patron_log = re.compile(
    r'(?P<fecha>\d{4}-\d{2}-\d{2}) (?P<hora>\d{2}:\d{2}:\d{2}) '
    r'\[(?P<nivel>\w+)\] (?P<server>[\w\-]+) - '
    r'(?P<mensaje>.+?) - status=(?P<status>\d+)'
)

filas = [m.groupdict() for linea in logs.strip().splitlines()
         if (m := patron_log.search(linea))]

df_logs = pd.DataFrame(filas)
df_logs

,fecha,hora,nivel,server,mensaje,status
0,2026-03-05,03:12:01,INFO,server-01,Request GET /api/usuarios completed in 120ms,200
1,2026-03-05,03:12:45,ERROR,server-02,Database connection timeout after 5000ms,503
2,2026-03-05,03:13:02,INFO,server-01,Request POST /api/login completed in 89ms,200
3,2026-03-05,03:13:15,WARN,server-01,Memory usage at 87% threshold,200
4,2026-03-05,03:14:00,ERROR,server-03,Database connection timeout after 5000ms,503
5,2026-03-05,03:14:22,INFO,server-02,Request GET /api/productos completed in 340ms,200
6,2026-03-05,03:15:01,ERROR,server-01,Null pointer exception in PaymentService,500
7,2026-03-05,03:15:30,INFO,server-03,Request GET /api/usuarios completed in 95ms,200
8,2026-03-05,03:16:10,ERROR,server-02,Database connection timeout after 5000ms,503
9,2026-03-05,03:16:45,WARN,server-01,Memory usage at 91% threshold,200
10,2026-03-05,03:17:20,ERROR,server-03,Null pointer exception in PaymentService,500
11,2026-03-05,03:18:00,INFO,server-01,Request POST /api/checkout completed in 210ms,200
12,2026-03-05,03:18:33,ERROR,server-02,Database connection timeout after 5000ms,503

In [16]:
# Pregunta de negocio: ¿qué servidor está fallando más?
errores = df_logs[df_logs['nivel'] == 'ERROR']
errores['server'].value_counts()

server
server-02    3
server-03    2
server-01    1
Name: count, dtype: int64

**Lectura de negocio:** `server-02` concentra la mayoría de los errores — y específicamente errores de timeout de base de datos. Eso ya es una pista concreta para el equipo de infraestructura: no es "el sistema está lento", es "server-02 tiene un problema de conexión a la base de datos".

---
## **Ejercicio:** el patrón que se repite

En los 3 casos hicimos exactamente lo mismo:

1. **Encontrar** — `re.search` con un patrón simple para filtrar
2. **Extraer** — grupos nombrados `(?P<nombre>...)` para capturar campos de un registro
3. **Estructurar** — aplicar el patrón a todas las líneas, construir un DataFrame, y agrupar/contar para responder una pregunta de negocio

Esa progresión —no la sintaxis específica de cada regex— es lo que vale la pena que se lleven del taller.

### Ejercicio para practicar

Abajo tienes un cuarto dataset, de **reviews de productos**, sin resolver. Aplica la misma progresión:

1. Encuentra las reviews con calificación de 1 o 2 estrellas
2. Extrae los campos: fecha, producto, calificación, comentario
3. Construye una tabla y responde: ¿qué producto tiene más quejas?

In [17]:
reviews = """
[2026-03-01] PRODUCTO: Audífonos BT-200 | CALIFICACION: 5 estrellas | Comentario: Excelente sonido, muy cómodos.
[2026-03-01] PRODUCTO: Cargador USB-C 65W | CALIFICACION: 2 estrellas | Comentario: Dejó de funcionar a la semana.
[2026-03-02] PRODUCTO: Audífonos BT-200 | CALIFICACION: 1 estrellas | Comentario: Se desconectan solos cada 5 minutos.
[2026-03-02] PRODUCTO: Mouse Inalámbrico M1 | CALIFICACION: 4 estrellas | Comentario: Bueno, un poco pesado.
[2026-03-03] PRODUCTO: Cargador USB-C 65W | CALIFICACION: 1 estrellas | Comentario: Llegó dañado, no carga nada.
[2026-03-03] PRODUCTO: Audífonos BT-200 | CALIFICACION: 2 estrellas | Comentario: El micrófono no se escucha bien.
[2026-03-04] PRODUCTO: Teclado Mecánico K3 | CALIFICACION: 5 estrellas | Comentario: Excelente para programar.
[2026-03-04] PRODUCTO: Cargador USB-C 65W | CALIFICACION: 2 estrellas | Comentario: Se calienta demasiado.
"""

# Tu código aquí